name: popup_menu_2
description: a pupup menu, contains clickable buttons each, and a global click function referring the item, this is for porpose not break the user attention,.
repository: https://github.com/ymrabti/popup_menu_2.git
# publish_to: https://pub.dev

version: 0.1.4-beta.2

environment:
    sdk: ^3.5.4

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^1.0.0

flutter:
    uses-material-design: true
